### ISSUE TITLE
Implement Dark Mode Feature using Tailwind CSS Dark class

### ISSUE THREAD

**Issue by abhideepkumar** [abhideepkumar/sigmaevents#1]
Implement a toggle button to switch between light and dark mode on a website.

**Comment by abhideepkumar** [comment]
Ok, use tailwind CSS to implement dark mode.

**Comment by Dhananjayshukla1** [comment]
ok

**Comment by Archit5655** [comment]
@abhideepkumar  I can apply this feature smoothly.
can you please assign me this issue

**Comment by abhideepkumar** [comment]
I have assigned to both of you. The best implementation will be accepted.

**Comment by Archit5655** [comment]
hey @abhideepkumar  had a small doubt you want darkmode on the home page or on all the pages ?

**Comment by abhideepkumar** [comment]
On all the pages and use tailwind dark mode
https://tailwindcss.com/docs/dark-mode

**Comment by Archit5655** [comment]
ook and I am going to use context API for managing the state of dark mode fine with you?

**Comment by abhideepkumar** [comment]
No, use the dark mode of Tailwind css and add toggle mode from it also.Add three options to toggle Light, Dark and System Preference. 
Go through that docs and implement it.
Don't use Context Api.

**Comment by Archit5655** [comment]
got  it👍

**Comment by Archit5655** [comment]
ok.   I  had made a single button which gets toggle dark mode on clicking and changes the icon .
and initially when the user comes its theme would be automatically set to its system preference .
 I think 3 separate icons for toggle the theme would unnecessary be congesticatinfg the navbar .
what do you think which approach should I go with @abhideepkumar

**Comment by Archit5655** [comment]
ok.   I  had made a single button that toggles dark mode on clicking and changes the icon .
and initially when the user comes its theme would be automatically set to its system preference.
I think 3 separate icons for toggle the theme would unnecessarily be congesting the navbar.
what do you think which approach should I go with @abhideepkumar
