### ISSUE TITLE
Adding home route to the logo  in navbar

### ISSUE THREAD

**Issue by Archit5655** [abhideepkumar/sigmaevents#12]
![Screenshot 2024-01-01 224214](https://github.com/abhideepkumar/sigmaevents/assets/112563353/0b9c8335-8493-4fdc-81e5-3d5441dcbb85)
The logo icon in the navbar when clicking doesn't head to the home route also the curson is not a pointer

**Comment by abhideepkumar** [comment]
We have a Home button so there is no need to route to home.
