### ISSUE TITLE
Improve the loading UI

### ISSUE THREAD

**Issue by thesurajdas** [abhideepkumar/sigmaevents#18]
![image](https://github.com/abhideepkumar/sigmaevents/assets/44750499/d05c387b-2f95-4f58-a8ae-a7b9d2954258)
I would like to update a custom loading design and I am sure you will like it. I also joined SWOCS4 as a contributor.

**Comment by abhideepkumar** [comment]
ok, sure

**Comment by thesurajdas** [comment]
![image](https://github.com/abhideepkumar/sigmaevents/assets/44750499/cb6363ed-7ef8-49f9-b620-f5d4e8bac1d6)
is this design ok for loading event cards?
Let me know if you need any changes or I send you the pull request with these changes.
