### ISSUE TITLE
Improving Card UI in "Events" page and applying modern UI 

### ISSUE THREAD

**Issue by Kunal-Khairnar-05** [abhideepkumar/sigmaevents#19]
This pull request proposes potential improvements to the UI of the event cards. I haven't implemented these changes yet, but I wanted to get feedback on the suggestions before starting.

Proposed changes:

* Increase font size and line height for easier readability.
* Add Hover Effect on image in the card
* Add a bold title for improved scan ability.
* Include icons for location and date/time for visual appeal and clarity.

---
![Screenshot 2024-01-04 190924](https://github.com/abhideepkumar/sigmaevents/assets/95234444/a7d8351b-582b-4942-9a35-762e0b614249)

**Comment by abhideepkumar** [comment]
ya sure, use tailwind CSS to improve the UI and also use modern, minimalist icons.
Make sure to make it responsive and also prevent using vanilla JavaScript.

**Comment by Kunal-Khairnar-05** [comment]
I would be grateful if you could assign this issue to me.

**Comment by Kunal-Khairnar-05** [comment]
PR has been raised for resolution of this issue by me.

**Comment by abhideepkumar** [comment]
You have not updated your branch with the latest commits. To get the most recent changes, you should run git fetch and then resolve any conflicts.
Always check for new commits in the forked repository before coding and work on them to avoid conflicts.
If you have any difficulties, feel free to ask here.

**Comment by abhideepkumar** [comment]
@JrG-One, can you work on this also if possible.
Replace the text of the keys with icons and add a new row for Organizer. The Organizer row should display a small logo and a name on the same line. If event.organizer is not specified, use "unknown" as the name. Format the date and time on a single line.
The final layout should look like this:
Title (with deadline next to it)
Description (two lines maximum, horizontally scrollable if longer)
Date and time in one line
Organizer logo and name

**Comment by abhideepkumar** [comment]
and @Kunal-Khairnar-05 if you are still interested to work on this issue then reply back.

**Comment by Kunal-Khairnar-05** [comment]
Yes I am working on it
