### ISSUE TITLE
Feat: Improvement in home page

### ISSUE THREAD

**Issue by Yatin12527** [abhideepkumar/sigmaevents#20]
I think home page looks too simple and plain i can update it to look more interactive and use better styles and color combination.
![image](https://github.com/abhideepkumar/sigmaevents/assets/134225415/ca6a49ac-c97f-40cd-a0b8-29fd934d7917)

**Comment by abhideepkumar** [comment]
Y, sure but before working, please tell me how it will look after, and do you then need to change the style of navbar as well?

**Comment by Yatin12527** [comment]
i'll create a pr for the new designed page you can merge it if u like the design or if tell me whatever fixes you would like to have in it.
