### ISSUE TITLE
 Fix Image Loading in AllEvents Component

### ISSUE THREAD

**Issue by abhideepkumar** [abhideepkumar/sigmaevents#4]
It takes a lot of time to load images so you can add a low-resolution image to show until the actual image loads.

**Comment by PulastTiwari** [comment]
Could you assign this to me under SWOC 24 @abhideepkumar

**Comment by PulastTiwari** [comment]
could you assign this to me under SWOC24 @abhideepkumar

**Comment by venkataraviraja5** [comment]
Can you please assign to me i would like to work on this

**Comment by abhideepkumar** [comment]
I assigned you, and before working tell me what u are going to do to fix this.

**Comment by venkataraviraja5** [comment]
i would like to add shimmer ui like in youtube if you have any thoughts please comment

**Comment by abhideepkumar** [comment]
Ya sure, go for it.

**Comment by venkataraviraja5** [comment]
![Screenshot 2024-01-01 200809](https://github.com/abhideepkumar/sigmaevents/assets/131418248/3954d049-1110-4f1f-b232-7d8fbe26225a)

i am not able to fetch data from API can you help me

**Comment by abhideepkumar** [comment]
Have you setup the env variables? Read the readme file again and make sure that every steps you followed well.

**Comment by venkataraviraja5** [comment]
okay

**Comment by venkataraviraja5** [comment]
![Screenshot 2024-01-02 094702](https://github.com/abhideepkumar/sigmaevents/assets/131418248/7ac59b5c-886b-4965-9e55-ef5f2f278223)

example.env file doesnt exist can you help me

**Comment by abhideepkumar** [comment]
I added the file recently so I think you must be using the last pulled code. So, run git pull to pull the last code and then you will see example.env.local

**Comment by venkataraviraja5** [comment]
okay

**Comment by venkataraviraja5** [comment]
![Screenshot 2024-01-02 100021](https://github.com/abhideepkumar/sigmaevents/assets/131418248/3990e77c-7f2a-4b1f-8a54-18724bf9ec36)

its showing upto data

**Comment by venkataraviraja5** [comment]
it is updated in repo but am not getting that file in my system can i add .env file in my system

**Comment by abhideepkumar** [comment]
.env works in React js and this is a Next js project so, you need to create .env.local file name and yes create it and add all env variables because without that you can't work.

**Comment by venkataraviraja5** [comment]
okay

**Comment by abhideepkumar** [comment]
are you working on this.

**Comment by venkataraviraja5** [comment]
![Screenshot 2024-01-05 111220](https://github.com/abhideepkumar/sigmaevents/assets/131418248/b6470591-b5a6-4edd-be4a-8c5ea2e28da8)

hey i updated with my values still am getting same error

**Comment by venkataraviraja5** [comment]
![Screenshot 2024-01-05 111330](https://github.com/abhideepkumar/sigmaevents/assets/131418248/f79e6975-c0a5-45e4-b1f7-e8cbd2794245)

this is my client id and secret right

**Comment by abhideepkumar** [comment]
ya these are the client id and secret.
And delete this. You must prevent your api to expose on an open platform.
Try asking these in private chats like linkedin.

**Comment by abhideepkumar** [comment]
Actually, no u can put dummy data where it is mapping from database and u can comment the fetch part to stop this error. And once you change the UI then change the mapping and fetch part to what it should be.

**Comment by venkataraviraja5** [comment]
okay @abhideepkumar

**Comment by venkataraviraja5** [comment]
hey i have sent you message on lkdn can you please tell me when you will free

**Comment by abhideepkumar** [comment]
Hi, this issue is already fixed in #18 issue.
