### ISSUE TITLE
 Add icons on Navbar for menu items

### ISSUE THREAD

**Issue by Ishita928** [abhideepkumar/sigmaevents#43]
We need to improve:
Icons for each button can be added alongside with the text on the Navbar to make it look more appealing
![image](https://github.com/abhideepkumar/sigmaevents/assets/146575485/7648ff46-cc37-4793-b8b6-47a71c1930c5)

**Comment by abhideepkumar** [comment]
can you make a design first to show how it will look after.
You can make it in any software even in Canva.

**Comment by Ishita928** [comment]
sure ,I will make the design first and then you can review it

**Comment by Ishita928** [comment]
![image](https://github.com/abhideepkumar/sigmaevents/assets/146575485/1778d611-979d-437d-a12b-6169c9c097c6)
it will look something like this , a rough idea of the styling

**Comment by Ishita928** [comment]
Okay ,no problem , thanks for your response
