### ISSUE TITLE
 Implement Post-event Attendee Feedback Sharing

### ISSUE THREAD

**Issue by abhideepkumar** [abhideepkumar/sigmaevents#8]
Develop a feature that enables organizers to share post-event feedback from attendees to encourage continuous improvement and engagement.

**Comment by JrG-One** [comment]
i can work on it, Please assign me 
I'm Contributor under Social Winter of Code 2024

**Comment by abhideepkumar** [comment]
Ok, make a new component Footer and then render it to the Homepage

**Comment by abhideepkumar** [comment]
Ya sure, check for time is passed or not and then add a Feedback button in Registered Button. If Feedback is also submitted, then make a popup of Feedback already submitted.

**Comment by JrG-One** [comment]
![image](https://github.com/abhideepkumar/sigmaevents/assets/118374998/4e397868-4ef8-4545-8e7a-aedad8164005)

i've made this section on homepage 
like if user is already login then submit button will appear if not then Login to submit button will appear

**Comment by abhideepkumar** [comment]
You understood the issue wrong.
The issue is to add a feedback button to every event once the event has started.
On Clicking on the Feedback button, a screen will popup which will ask for the Rating and Feedback message which will be sent to the MongoDB database.

**Comment by JrG-One** [comment]
i'm facinmg problem while connecting to Mongo DB 
could please share the steps to connect MongoDB

**Comment by JrG-One** [comment]
@abhideepkumar, I've added a feedback button following your instructions. Below, I've provided an example event along with a screenshot to demonstrate. I'm working on creating a general code that will function for all events.
![image](https://github.com/abhideepkumar/sigmaevents/assets/118374998/01bb6c3d-2beb-4bbb-81db-126d3c47cf6e)

**Comment by JrG-One** [comment]
@abhideepkumar, I didn't hear back from you. Is it correct, or do I need to make any changes? If possible, please clarify this issue so I can work on the other issues you assigned me.

**Comment by abhideepkumar** [comment]
You added all the code in allevents compoenent. make a new component feeback.js and put all code and also if you know MongoDB then use data api to add the data to database.

**Comment by abhideepkumar** [comment]
You have not updated your branch with the latest commits. To get the most recent changes, you should run git fetch and then resolve any conflicts.
Always check for new commits in the forked repository before coding and work on them to avoid conflicts.
If you have any difficulties, feel free to ask here.

**Comment by JrG-One** [comment]
@abhideepkumar i've reoslved it please check now

**Comment by abhideepkumar** [comment]
i have merged your pr.
