### ISSUE TITLE
Footer need to be Fixed

### ISSUE THREAD

**Issue by JrG-One** [abhideepkumar/sigmaevents#9]
The CSS for the footer is currently not stable, and I'm confident that I can resolve this issue. Kindly assign it to me, as I am a contributor participating in the Social Winter of Code 2024.

**Comment by abhideepkumar** [comment]
Ok, make a new component Footer and then render it to the Homepage

**Comment by abhideepkumar** [comment]
Hey are you still working on this?

**Comment by JrG-One** [comment]
Yes i;m working on this issue and issue #8 collaboartively, 
will raise PR for both by tommorow

**Comment by abhideepkumar** [comment]
refer to #22 for further discussion on this.
